export type Calculation = {
  id: string;
  name: string;
  notes: string | null;
  category: string | null;
  status: "draft" | "validated" | "archived" | null;
  favorite: boolean | null;
  user_id: string;
  cost: number;
  shipping_cost: number | null;
  platform_fees: number | null;
  payment_fees: number | null;
  time_hours: number | null;
  hourly_rate: number | null;
  total_cost: number | null;
  price: number;
  tva_rate: number | null;
  price_ttc: number | null;
  profit: number;
  margin: number;
  target_margin: number | null;
  suggested_price: number | null;
  low_price: number | null;
  recommended_price: number | null;
  premium_price: number | null;
  created_at: string;
  updated_at: string | null;
};

export type CalculationInput = {
  user_id: string;
  name?: string;
  notes?: string;
  category?: string;
  status?: "draft" | "validated" | "archived";
  favorite?: boolean;
  cost: number;
  shipping_cost?: number;
  platform_fees?: number;
  payment_fees?: number;
  time_hours?: number;
  hourly_rate?: number;
  total_cost?: number;
  price: number;
  tva_rate?: number;
  price_ttc?: number;
  profit: number;
  margin: number;
  target_margin?: number;
  suggested_price?: number;
  low_price?: number;
  recommended_price?: number;
  premium_price?: number;
};
